power<-read.table("household_power_consumption.txt",header=TRUE,sep=";",stringsAsFactors=FALSE)
power_subset<-subset(power,power$Date %in% c("1/2/2007","2/2/2007"))
library(lubridate)
date_time<-paste(power_subset$Date,power_subset$Time)
dt<-dmy_hms(date_time)
png(file="plot3.png",height=480,width=480)
plot(dt,power_subset$Sub_metering_1,type="l",xlab="",ylab="Energy sub metering")
points(dt,power_subset$Sub_metering_2,type="l",col="red")
points(dt,power_subset$Sub_metering_3,type="l",col="blue")
legend("topright",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),pch="-",lwd=1,cex=1,text.col=c("black","red","blue"))
dev.off()