power<-read.table("household_power_consumption.txt",header=TRUE,sep=";",stringsAsFactors=FALSE)
power_subset<-subset(power,power$Date %in% c("1/2/2007","2/2/2007"))
png(file = "plot1.png", width = 480, height = 480)
hist(as.numeric(power_subset$Global_active_power),xlab="Global Active Power (kilowatts)",ylab="Frequency",main="Global Active Power",col="red")
dev.off()